version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout
      - run:
          name: log Go version
          command: go version
      - run:
          name: run all tests
          command: go test -v ./...

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
