version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout
      - run:
          name: log Go version
          command: go version
      - test:
           pre:
             - go get github.com/mattn/goveralls
           override:
             - go test -v -cover -race -coverprofile=/home/ubuntu/coverage.out
           post:
             - /home/ubuntu/.go_workspace/bin/goveralls -coverprofile=/home/ubuntu/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
