version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    steps:
      - checkout
      - run:
          name: Log Go version
          command: go version
      - run:
          name: Run all tests
          command: make test

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
